version: '3.8'

services:
    backend-pairing-apache:
        container_name: php-apache
        build: ./
        volumes:
            - ./app:/var/www/html
            - ./docker/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        ports:
          - 80:80
          - 443:443
        networks:
            - backend-pairing-net

networks:
    backend-pairing-net:
        name: backend-pairing-net